I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 168, in script
    claragracia "My name's Clara. I lost my eldest, Sebastián, in Guyana."
Exception: Sayer 'claragracia' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 168, in script
    claragracia "My name's Clara. I lost my eldest, Sebastián, in Guyana."
  File "/home/morgan/Documents/renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/morgan/Documents/renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'claragracia' is not defined.

Linux-5.13.0-27-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.11.2266
Majnun 1.0
Mon Jan 31 15:00:44 2022
